---
# task file for jetty-remove.yml

- name: "Stop jetty service"
  become: true
  become_method: sudo
  ansible.builtin.systemd_service:
    name: "jetty"
    state: stopped

- name: "Delete all files and dirs installed"
  ansible.builtin.shell: "rm -rf /usr/local/src/jetty-* /opt/jetty/ /var/log/jetty/ /etc/default/jetty /etc/init.d/jetty /run/jetty /run/systemd/generator.late/jetty.service /run/systemd/generator.late/*/jetty.service /run/systemd/units/invocation:jetty.service /etc/rc*.d/*jetty /tmp/hsperfdata_jetty/"

- name: "Remove the 'jetty' user"
  ansible.builtin.user:
    name: "jetty"
    state: "absent"
    remove: yes

- name: "Remove the 'jetty' group"
  ansible.builtin.group:
    name: "jetty"
    state: "absent"