---
# tasks file for jdk role

- name: "Install Amazon Corretto JDK"
  ansible.builtin.import_tasks: "jdk-install.yml"
  tags: jdk

- name: "Remove Amazon Corretto JDK"
  ansible.builtin.import_tasks: jdk-remove.yml
  tags: [ never, jdk-remove, remove ]